- examples/ownership-transfer/README.md
- examples/ownership-transfer/package-lock.json
- examples/ownership-transfer/package.json
- examples/ownership-transfer/src/@types/interface-datastore/index.d.ts
- examples/ownership-transfer/src/index.ts
- examples/ownership-transfer/transfer.js
- examples/ownership-transfer/tsconfig.json
Add an example program demonstrating ownership transfer.
> Add example of ownership transfer

- examples/tokens/index.ts
- examples/tokens/package-lock.json
- examples/tokens/package.json
- examples/tokens/readme.md
- examples/tokens/src/@types/interface-datastore/index.d.ts
- examples/tokens/src/@types/uuid/v4/index.d.ts
- examples/tokens/src/index.ts
- examples/tokens/tsconfig.json
This is a typescript example for sending/receiving tokens.
> add a token transfer example

- examples/set-and-get-data/README.md
- examples/set-and-get-data/package-lock.json
- examples/set-and-get-data/package.json
- examples/set-and-get-data/src/@types/interface-datastore/index.d.ts
- examples/set-and-get-data/src/index.ts
- examples/set-and-get-data/tsconfig.json
Add example where one sets and gets data.
> Add example of setting and getting data

- README.md
> Document examples and explorer in README

- src/community/default.ts
- wasmtupelo/docker-compose.yml
Adds the two new nodes, switches community to master
> community updates

- examples/ownership-transfer/src/index.ts
- examples/tokens/src/index.ts
Noticed this when demoing on the IPFS weekly call. These DIDs are useful so that you can go over to the explorer and look at what happened.
> show the DIDs on the examples

- src/community/community.ts
> fix typo in docs

- etc/tupelo-wasm-sdk.api.md
- src/community/messaging.spec.ts
- src/community/messaging.ts
- src/tupelo.ts
I need/want this for decentracar... this pretty simply makes an "unsubscribe" for community messaging (as opposed to the underlying js pubsub unsubscribe)
> allow unsubscribe from community messages

- .github/workflows/examples.yml
- .github/workflows/test.yml
- examples/set-and-get-data/src/index.ts
- scripts/ci-build.sh
- scripts/ci-gitsetup.sh
- src/crypto.spec.ts
- src/js/p2p/discovery.js
This adds a github action for CI and does a tiny bit of logging cleanup
> add github actions

- examples/ownership-transfer/package.json
- examples/set-and-get-data/package.json
- examples/tokens/package.json
- package-lock.json
- package.json
changes necessary to move to v0.0.12
> upgrade to 0.0.12

- examples/set-and-get-data/package-lock.json
- examples/set-and-get-data/src/index.ts
This makes the set-data example more resilient to timing from community varying by retrying on a "not found"
> set-data resiliency

- examples/set-and-get-data/package-lock.json
oops - bad integrity from local testing was checked in.
> fix package-lock of set-and-get-data example

- etc/tupelo-wasm-sdk.api.md
- src/tupelo.spec.ts
- src/tupelo.ts
This exposes the verifyCurrentState to the javascript SDK
> expose the new verifyCurrentState

- src/community/community.spec.ts
- src/legacy/legacy.spec.ts
@brandonwestcott found an intermittent test failure, documented in #40. This adds a fix for that failure and another one I noticed while debugging. This just retries the commands until the notfound is gone.
This fixes the spec, one wonders if this should be in the SDK somewhere, but it's not immediately obvious how to do that generically.
> looping retries

- examples/ownership-transfer/package-lock.json
- examples/ownership-transfer/package.json
- examples/set-and-get-data/package-lock.json
- examples/set-and-get-data/package.json
- examples/tokens/package-lock.json
- examples/tokens/package.json
I believe this is what we discussed with the examples? Using 'latest' instead of a specific version number and instead of a file://..
> use 'latest' in the examples

- .dockerignore
- browsertest/package-lock.json
- etc/tupelo-wasm-sdk.api.md
- package-lock.json
- package.json
- scripts/test-suite.sh
- src/chaintree/chaintree.ts
- src/community/community.spec.ts
- src/community/community.ts
- src/tupelo.spec.ts
- src/tupelo.ts
again, i think this gets everything for the new message interfaces, but please double check I got allthethings
depends on https://github.com/quorumcontrol/tupelo-go-sdk/pull/154 and https://github.com/quorumcontrol/community/pull/56
> updates for v2 messages

- .github/workflows/examples.yml
- examples/ownership-transfer/package-lock.json
- examples/set-and-get-data/package-lock.json
- examples/tokens/package-lock.json
small example updates to bring the package-lock.json files up to date (which seems to make them work better on my machine). Also fixes a typo in the github actions.
> update the package.locks and fix a typo in the examples

- scripts/test-suite.sh
this takes the go-sdk up to master.
> upgrade to go-sdk master

- src/community/default.ts
this is the *quick* fix for why getDefaultCommunity() still wasn't working in browser. The meat is just changing the order to wss then tcp as opposed to tcp then wss. Should probably figure out a way to keep it in any order - but this restores the functionality.
> put wss on top of tcp

- etc/tupelo-wasm-sdk.api.md
- src/community/community.ts
- src/community/default.ts
Tests pass pretty reliably (locally; we'll see shortly about CI) with this change.
> Wait until connected to 2/3+ of signers

- src/repo.spec.ts
- src/repo.ts
simply adds delete to repo which I found useful for "logout"
> add delete to repo

- .github/workflows/publish.yml
- etc/tupelo-wasm-sdk.api.md
- package-lock.json
- package.json
> version to v0.6.0-rc7

- package-lock.json
- package.json
> bump version to v0.6.0-rc8

- examples/ownership-transfer/src/index.ts
We had 2 requests for "how do I see the ownership history" so I figured I'd add ownership history to the setOwnership example.
> show ownership history in the example

- package-lock.json
- package.json
I was playing around with runkit and importing the sdk had an error - looks like package.json is missing the ipld-dag-cbor dependency even though it's required in a couple of files.
> add ipld-dag-cbor

- package-lock.json
- package.json
Bumps version - go v1.14 is the big change here.
> version bump to v0.6.3

- package-lock.json
- package.json
> bump to v0.7.3
