README.md
etc/tupelo-wasm-sdk.api.md
src/community/community.ts
src/community/default.integration.ts
src/community/default.ts
src/community/index.ts

This moves the getDefault function into the Community namespace. It's a breaking api... so will need to update the explorer and examples. I think this is a good time to do that though.

getDefault move

---

etc/tupelo-wasm-sdk.api.md
src/community/community.ts
src/community/messaging.spec.ts
src/community/messaging.ts

Noticed that DIDs are trying to be base64d by protobuf for some reason (I think because of the ':'). This switches local identifier to match the protobuf
Also adds a type to the getTip method return.

touchups to the messaging interface

---

.github/workflows/test.yml
.npmignore
builddocker/Dockerfile
builddocker/docker-compose.yml
package.json
scripts/_docker-build.sh
scripts/build-wasm.sh
src/js/go/index.js

This moves the wasm build into docker - write now pointing at https://github.com/quorumcontrol/tupelo-go-sdk/pull/129
This makes a slightly smaller wasm file (32MB) and should improve memory usage (due to the byte copying)

go 1.13 WASM build

---

src/js/go/index.js

lost this along the way somewhere, but in the browser one needs a pid and title because our logging library uses those. Go seems to have left that out of their default by accident.
We *used* to have this code somewhere, but I must have accidentally ripped it out somewhere along the line.

add pid and title to browser env

---

src/community/community.ts
src/community/default.integration.ts
src/community/default.ts

Noticed by a community member, sometimes calling getDefault was returning different communities. I believe that was due to the differing async calls here. This cleans that up so that the check and return is always happening in a sync call and not in promises.

cleanup handling of calling getDefault multiple times

---

src/chaintree/chaintree.spec.ts
src/chaintree/chaintree.ts
src/chaintree/dag/dag.spec.ts
src/chaintree/dag/dag.ts

most of this is tests, but this adds resolveData to chaintree and also allows resolve(At) to take a string argument. It still allows arrays, but prints a deprecation warning.

add resolveData and switch resolve to strings

---

wasmtupelo/configs/community2.toml
wasmtupelo/docker-compose.yml

This adds a second community because wasm does interact in a different way with multiple sources of truth with differing communities and it's fairly low overhead, so it makes sense to simulate that.

add a second community because multiple tips is a realistic interaction

---

package-lock.json
package.json

Also examples have `package.json` and `package-lock.json` pegged to `v0.0.13` - bumping those requires npm publish, which should come after doing the release & pr here. Should we change those to be `"tupelo-wasm-sdk": "../../"`? Downside there is someone couldn't checkout this repo, move the examples folder to somewhere else, and try and run

Bump version to v0.5.0

---

.github/workflows/publish.yml
scripts/ci-release-ver-check.sh

Publish releases to npm whenever a new github release is published. Decided to go ahead and run tests as preflight to publishing

Add npm publish workflow

---

etc/tupelo-wasm-sdk.api.md
src/tupelo.ts

Fixes this bug: https://trello.com/c/LmSngdNr
Actual changes are in `src/tupelo.ts`. Markdown changes were generated by the new build.

Fix wasm multi load

---

package-lock.json
package.json

Updates `tupelo-go-sdk` which sets `MaxPlayTransactionsAttempts` to 1 for wasm, avoiding the unsupported `GetTip` call in the retry loop of `PlayTransactions`

fix GetTip panic by avoiding retrys on PlayTransactions

---

src/community/local.ts

Going to do a 2 part fix here. In this PR, I'm reverting the `local.ts` to use a hardcoded string rather than referencing the `testNotaryGroup`.
As a follow up to make this all more robust, my proposal is to build off the work from https://github.com/quorumcontrol/tupelo-wasm-sdk/pull/48 and support a path based loader that can switch between `fs` and `http` requests.

Skip fs loading in order to fix browser

---

etc/tupelo-wasm-sdk.api.md
src/community/community.spec.ts
src/community/community.ts
src/constants.spec.ts

Noticed a lot of boiler plate when you just want to connect to a different notary group (h/t @brandonwestcott ). This PR adds a `Community.fromNotaryGroupToml` method that takes a toml config and gives you back a connected community (and takes an optional repo).

expose a community from toml builder

---

.gitignore
browsertest/tupelo.wasm

forgot to symlink the tupelo.wasm into the browser tests to make sure it's available. I'll keep my clownshoes ChainTree for this one.

symlink to the built tupelo.wasm which is necessary in the tests

---

etc/tupelo-wasm-sdk.api.md
src/crypto.spec.ts
src/crypto.ts
src/tupelo.spec.ts
src/tupelo.ts

This branch uses the https://github.com/quorumcontrol/tupelo-go-sdk/pull/157/files branch of tupelo-go-sdk and allows an EcdsaKey to generate a signature

allows signing/verifying of arbitrary messages

---

.github/workflows/publish.yml
.npmignore
package-lock.json
package.json

in attempting to publish a pre-release I accidentally published the new wasm-sdk out to latest and required doing an emergency release of v0.5.15 (same as v0.5.14) in order to overwrite (unpublish didn't work).
This bumps this up to the current release (2.0.0-pre) and also adds the "next" tag for now when releasing until tupelo is also released with a testnet (at which point we should remove next)... but adding next lets us do the normal release path through github for now while not auto-upgrading our builders.

release bump

---

scripts/test-suite.sh

docker-compose already has this default, and removing allows tupelo version switched per script execution

Remove TUPELO_VERSION from test-suite

---

etc/tupelo-wasm-sdk.api.md
src/community/community.spec.ts
src/community/community.ts
src/community/default.ts
src/js/p2p/discovery.js
src/js/p2p/index.js
src/node.spec.ts
src/node.ts

This makes the RoutingDiscovery use the namespace specified in the NotaryGroup. One note, I made the `namespace` optional, defaulting to a noop / null router. Went back and forth if thats necessary interface though.

Use discovery namespace from notary group

---

etc/tupelo-wasm-sdk.api.md
src/community/community.spec.ts
src/community/community.ts
src/community/default.ts
src/js/p2p/discovery.js
src/js/p2p/index.js
src/node.spec.ts
src/node.ts
src/notarygroup.spec.ts
src/notarygroup.ts

This has #70 in it as well, but this waits until one signer is connected (instead of counting just the number of peers).

wait for a signer

---

src/js/p2p/index.js
src/js/p2p/wss-peer-book.js
src/js/p2p/wss-peer-book.spec.ts

This updates the libp2p node to use only WSS addresses when running within the browser under https.

Use only WSS addrs in HTTPS

---

docker-compose.yml
localtupelo/configs/node1/config.toml
localtupelo/configs/node2/config.toml

Sometimes tests were failing on that first tupelo playtransaction - after debugging, it was only passing when the first connected peer was `node0` from docker-compose. Exposing the ports on the other nodes seems to make it consistently 💚

make tests work consistently

---

src/chaintree/chaintree.spec.ts
src/chaintree/chaintree.ts
src/tupelo.spec.ts
src/tupelo.ts

This upgrades the go-sdk (past master to https://github.com/quorumcontrol/tupelo-go-sdk/pull/202)
It also adds `ChainTree.getLatest(did)` which will use the go-sdk to do a getLatest and then return a ChainTree with the latest tip already in local storage.

add get latest

---

src/community/community.ts
src/community/default.ts

There seems to be an issue with discovering some of the signers in the notary group. This is a quick-fix to unblock release testing which adds in the signer WSS addresses to bootstrap.

quick fix to unblock testing, hard-codes the signer WSS addresses

---

.github/workflows/publish.yml

The latest 0.6.0 tag wasn't pushed to latest so it won't be the default. This fixes it so master now publishes @latest . See: https://www.npmjs.com/package/tupelo-wasm-sdk (versions).

switch back to using @latest tag

---

browsertest/package-lock.json
localtupelo/configs/localdocker.toml
src/js/go/index.js
src/js/go/wasm_exec.js
src/js/p2p/index.js

I noticed this while testing the latest code in the browser. I missed a few places where we modified the go wasm_exec.js which are specific to the browser (nodejs tests were passing).
This fixes those last few things and the browsertest tests pass again.

1.14 fixes for the browser

---

.gitmodules
scripts/_docker-build.sh

This just moves the wasm-sdk over to the new consolidated repo which contains the SDK now.

use the new consolidated repo

---

src/js/go/wasm_exec.js

This could be a node version thing maybe but in my node 13, I was getting an error: 
```
> const c = await sdk.Community.getDefault()
(node:85183) UnhandledPromiseRejectionWarning: TypeError: crypto.getRandomValues is not a function
at runtime.getRandomData (/Users/tobowers/code/tupelo-wasm-sdk/lib/js/go/wasm_exec.js:339:14)
at wasm-function[1045]:0xd75c2
at wasm-function[586]:0x80336
at wasm-function[970]:0xd4685
at wasm-function[1022]:0xd72c4
at global.Go.run (/Users/tobowers/code/tupelo-wasm-sdk/lib/js/go/wasm_exec.js:542:23)
at Object.run (/Users/tobowers/code/tupelo-wasm-sdk/lib/js/go/index.js:76:19)
(node:85183) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a …
```

fix getRandomValues() so that it works in our environment

---

src/chaintree/chaintree.spec.ts

This adds tests for grafting. You'll notice one is failing (grafting through an intermediary tree). Hence opening as a draft.

test the various grafting scenarios

---

src/tupelo.ts

I forgot to expose this function on the wasm side. This patch does that.

expose the newNamedTree function to sdk clients
